### ISSUE TITLE
EnvironmentNormalizer tried to normalize object

### ISSUE THREAD

**Issue by Ronnie-J** [flint/tacker#8]
Hi Henrik.

This issue is on version 1.2.1of flint/tacker. 
I haven't upgraded due to the dependencies for Pimple 1.0 and Silex 1.3

I have a security configuration like this:

```
security.firewalls:
    secret:
        pattern: "^/something"
        my_login:
            logout_return_path: '/logout/success'
            login_return_path: '/somepath
        users: %security.user_provider.my_login%
        logout:
            logout_path: '/somepath/logout'
```

```users: %security.user_provider.my_login%``` is picked up fine by the PimpleNormalizer but just after the EnvironmentNormalizer triggers and at this point tries to convert my object into a string which fails of course. Do you know why it would try and parse the object in the EnvironmentNormalizer since it was picked up by the PimpleNormalizer?

If I simply check for objects in the EnvironmentNormalizer and return if so then the code seems to run as expected.
